package com.fedevela.asic.formularios;

/**
 * Created by fvelazquez on 31/03/14.
 */
import com.fedevela.asic.util.LengthLimitedDocument;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.text.DefaultEditorKit;
import javax.swing.text.JTextComponent;
import javax.swing.text.Keymap;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author fvilla
 */
public class FrmRecapturaEx extends javax.swing.JDialog {

    private static final long serialVersionUID = -7489593841596132809L;
    private String checkValue;
    private boolean validated = false;
    private Object oldValue = null;

    public boolean isValidated() {
        return validated;
    }

    public void setValidated(boolean validated) {
        this.validated = validated;
    }

    /** Creates new form RecapturaForm */
    public FrmRecapturaEx(java.awt.Frame parent, boolean modal, String nombre, String value) {
        super(parent, modal);
        initComponents();
        init(nombre, value);
        dtValorTD19VC21.repaint();
        oldValue = value;
    }

    public FrmRecapturaEx(java.awt.Frame parent, boolean modal, String nombre, String value, String mask) throws ParseException {
        this(parent, modal, nombre, value);
        this.dtValorTD19VC21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(mask)));
    }

    public FrmRecapturaEx(Dialog owner, boolean modal, String nombre, String value, String mask) throws ParseException {
        this(owner, modal, nombre, value);
        this.dtValorTD19VC21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(mask)));
    }

    public FrmRecapturaEx(Dialog owner, boolean modal, String nombre, String value, javax.swing.text.MaskFormatter mask) throws ParseException {
        this(owner, modal, nombre, value);
        this.dtValorTD19VC21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mask));
    }

    public FrmRecapturaEx(Dialog owner, boolean modal, String nombre, String value, String mask, boolean isNumber ) throws ParseException {
        this(owner, modal, nombre, value);
        if( isNumber )
            this.dtValorTD19VC21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(mask))));
        else
            this.dtValorTD19VC21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(mask)));
    }

    public FrmRecapturaEx(Dialog owner, boolean modal, String nombre, String value) {
        super(owner, modal);
        initComponents();
        init(nombre, value);
        dtValorTD19VC21.repaint();
        oldValue = value;
    }

    public FrmRecapturaEx(Dialog owner, boolean modal, String nombre, String value, JPanel container) {
        super(owner, modal);
        initComponents();
        init(nombre, value, container);
        dtValorTD19VC21.repaint();
        oldValue = value;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRecaptura = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtValorTD19VC21 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("RECAPTURA");

        lblRecaptura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRecaptura.setText("Recaptura");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Recaptura y presiona ENTER para validar o ESC para regresar");

        try {
            dtValorTD19VC21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dtValorTD19VC21.setName("valor19"); // NOI18N
        dtValorTD19VC21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dtValorTD19VC21KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dtValorTD19VC21KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(lblRecaptura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dtValorTD19VC21, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblRecaptura)
                                        .addComponent(dtValorTD19VC21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dtValorTD19VC21KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtValorTD19VC21KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtValorTD19VC21KeyPressed

    private void dtValorTD19VC21KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtValorTD19VC21KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            if (StringUtils.equals(dtValorTD19VC21.getText(), checkValue)) {
                this.validated = true;
                this.setVisible(false);
                return;
            } else {
                return;
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dtValorTD19VC21.setText((String) oldValue);
            this.validated = false;
            this.setVisible(false);
            return;
        }
        if (StringUtils.equals(dtValorTD19VC21.getText(), checkValue)) {
            dtValorTD19VC21.setBackground(new Color(153, 255, 153));
        } else {
            dtValorTD19VC21.setBackground(new Color(255, 204, 204));
        }
    }//GEN-LAST:event_dtValorTD19VC21KeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dtValorTD19VC21;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblRecaptura;
    // End of variables declaration//GEN-END:variables

    private void init(String nombre, String value) {

        //Deshabilitando copy y paste de la recaptura
        JTextComponent.KeyBinding[] newBindings = {
                new JTextComponent.KeyBinding(
                        KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK),
                        DefaultEditorKit.beepAction),
                new JTextComponent.KeyBinding(
                        KeyStroke.getKeyStroke(KeyEvent.VK_V, InputEvent.CTRL_MASK),
                        DefaultEditorKit.beepAction),
                new JTextComponent.KeyBinding(
                        KeyStroke.getKeyStroke(KeyEvent.VK_X, InputEvent.CTRL_MASK),
                        DefaultEditorKit.beepAction)
        };

        Keymap k = dtValorTD19VC21.getKeymap();
        JTextComponent.loadKeymap(k, newBindings, dtValorTD19VC21.getActions());

        lblRecaptura.setText(nombre);
        dtValorTD19VC21.setDocument(new LengthLimitedDocument(StringUtils.length(value)));
        this.checkValue = value;
        Dimension dPantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dFormulario = getSize();
        setLocation(new Point((dPantalla.width - dFormulario.width) / 2,
                ((dPantalla.height - dFormulario.height) / 2) - 50));
    }

    private void init(String nombre, String value, JPanel panel ) {

        //Deshabilitando copy y paste de la recaptura
        JTextComponent.KeyBinding[] newBindings = {
                new JTextComponent.KeyBinding(
                        KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK),
                        DefaultEditorKit.beepAction),
                new JTextComponent.KeyBinding(
                        KeyStroke.getKeyStroke(KeyEvent.VK_V, InputEvent.CTRL_MASK),
                        DefaultEditorKit.beepAction),
                new JTextComponent.KeyBinding(
                        KeyStroke.getKeyStroke(KeyEvent.VK_X, InputEvent.CTRL_MASK),
                        DefaultEditorKit.beepAction)
        };

        Keymap k = dtValorTD19VC21.getKeymap();
        JTextComponent.loadKeymap(k, newBindings, dtValorTD19VC21.getActions());

        lblRecaptura.setText(nombre);
        dtValorTD19VC21.setDocument(new LengthLimitedDocument(StringUtils.length(value)));
        this.checkValue = value;
        Dimension dPantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dFormulario = getSize();
        setLocation(new Point( panel.getLocationOnScreen().x, ((dPantalla.height - dFormulario.height) / 2) - 50));
    }
}
